#!/bin/bash

#SBATCH --job-name=BNTB_BTB
#SBATCH --output=BNTB_BTB1.out
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=40
#SBATCH --partition=compute

ids=("BNTB19" "BNTB20" "BTB26" "BTB27" "BTB28" "BTB29" "BTB30") 
for id in "${ids[@]}"; do 

##Checking fastqc for files before trimming
fastqc -t 40 /lustre/muskan.g/run2_fastq_230620/"$id"_R1.fastq.gz -o /lustre/muskan.g/run2_fastq_230620/fastqc11
fastqc -t 40 /lustre/muskan.g/run2_fastq_230620/"$id"_R2.fastq.gz -o /lustre/muskan.g/run2_fastq_230620/fastqc11

  # Specify the input directory containing your paired-end read files
  input_dir=/lustre/muskan.g/run2_fastq_230620

  # Specify the output directory for the processed reads
  output_dir=/lustre/muskan.g/run2_fastq_230620/ttrimmed

  # Run Trimmomatic with the input and output file paths for the current sample
  trimmomatic PE -phred33 "${input_dir}"/"${id}"_R1.fastq.gz "${input_dir}"/"${id}"_R2.fastq.gz \
    "${output_dir}"/"${id}"_R1.paired.trimmed.fastq.gz "${output_dir}"/"${id}"_R1.unpaired.trimmed.fastq.gz \
    "${output_dir}"/"${id}"_R2.paired.trimmed.fastq.gz "${output_dir}"/"${id}"_R2.unpaired.trimmed.fastq.gz \
    ILLUMINACLIP:TruSeq3-PE-2.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36 -threads 8
    echo "Trimming completed!" 

  ## Checking fastqc for files after trimming
  fastqc -t 40 "${output_dir}"/"${id}"_R1.paired.trimmed.fastq.gz -o /lustre/muskan.g/run2_fastq_230620/fastqc22
  fastqc -t 40 "${output_dir}"/"${id}"_R2.paired.trimmed.fastq.gz -o /lustre/muskan.g/run2_fastq_230620/fastqc22

  echo "Quality check after trimming completed!"
done
